### ISSUE TITLE
List of upcoming events

### ISSUE THREAD

**Issue by EssBuilds** [EssBuilds/project-planning-demo#1]
**User story**
As a local resident, I want to see a list of upcoming community events.

**Acceptance Criteria**

- [ ] - The home page displays a list of events on the homepage that are sorted by date.
- [ ] - Each event in the list includes the event name, date, time, and a brief description.
- [ ] - The list is responsive and looks good on all main device sizes.

**Tasks**

- [ ] - Add an HTML section on the homepage dedicated to upcoming community events.
- [ ] - Style the event list using Bootstrap.
- [ ] - Add some sample events including event name, date, time and brief description.
